Repository sign-muscat/sorisonsoon-back, pull requests merged in 2024-08, with the labels that each got.

#20 #18 맞수수 미니 프로젝트 BE 리팩토링
  build.gradle
  config/DDL.sql
  config/DML.sql
  src/main/java/com/sorisonsoon/attachedfile/util/FileUploadUtils.java
  src/main/java/com/sorisonsoon/common/config/EmbeddingConfig.java
  src/main/java/com/sorisonsoon/common/config/QueryDslConfig.java
  src/main/java/com/sorisonsoon/common/config/SwaggerConfig.java
  src/main/java/com/sorisonsoon/common/controller/SettingTestController.java
  src/main/java/com/sorisonsoon/common/dto/response/ApiResponse.java
  src/main/java/com/sorisonsoon/common/dto/response/EmbeddingTestResponse.java
  src/main/java/com/sorisonsoon/common/exception/type/ExceptionCode.java
  src/main/java/com/sorisonsoon/common/swagger/config/SwaggerConfig.java
  src/main/java/com/sorisonsoon/common/swagger/controller/SwaggerController.java
  src/main/java/com/sorisonsoon/gameriddle/controller/GameRiddleController.java
  src/main/java/com/sorisonsoon/gameriddle/domain/entity/GameRiddle.java
  src/main/java/com/sorisonsoon/gameriddle/domain/entity/GameRiddleStep.java
  src/main/java/com/sorisonsoon/gameriddle/domain/repository/GameRiddleRepository.java
  src/main/java/com/sorisonsoon/gameriddle/domain/repository/GameRiddleRepositoryCustom.java
  src/main/java/com/sorisonsoon/gameriddle/domain/repository/GameRiddleRepositoryImpl.java
  src/main/java/com/sorisonsoon/gameriddle/domain/repository/GameRiddleStepRepository.java
  src/main/java/com/sorisonsoon/gameriddle/dto/response/HandQuestionResponse.java
  src/main/java/com/sorisonsoon/gameriddle/service/GameRiddleService.java
  src/main/java/com/sorisonsoon/gamevoice/domain/type/GameVoiceCategory.java
  src/main/java/com/sorisonsoon/user/domain/entity/User.java
Labels: ⚙️Setting, ✨ Feature, 🔧Refactor

#22 #16 허깅페이스 유사도 모델 셋팅 및 연결 및 동작 테스트
  build.gradle
  src/main/java/com/sorisonsoon/common/config/EmbeddingConfig.java
  src/main/java/com/sorisonsoon/common/controller/SettingTestController.java
  src/main/java/com/sorisonsoon/common/utils/pagination/PageResponse.java
  src/main/java/com/sorisonsoon/common/utils/pagination/Pagination.java
  src/main/java/com/sorisonsoon/common/utils/pagination/PagingButtonInfo.java
  src/test/java/com/sorisonsoon/common/config/EmbeddingConfigTests.java
Labels: ⚙️Setting, ✨ Feature

#26 #24 도소탐 BE 엔드포인트(with MariaDB) 구현
  src/main/java/com/sorisonsoon/gameChallenge/controller/GameChallengeController.java
  src/main/java/com/sorisonsoon/gameChallenge/domain/entity/GameChallenge.java
  src/main/java/com/sorisonsoon/gameChallenge/domain/repository/GameChallengeRepository.java
  src/main/java/com/sorisonsoon/gameChallenge/domain/repository/GameChallengeRepositoryCustom.java
  src/main/java/com/sorisonsoon/gameChallenge/domain/repository/GameChallengeRepositoryImpl.java
  src/main/java/com/sorisonsoon/gameChallenge/dto/request/SoundResultRequest.java
  src/main/java/com/sorisonsoon/gameChallenge/dto/response/SoundQuestionResponse.java
  src/main/java/com/sorisonsoon/gameChallenge/dto/response/SoundRecordResponse.java
  src/main/java/com/sorisonsoon/gameChallenge/dto/response/SoundResultResponse.java
  src/main/java/com/sorisonsoon/gameChallenge/service/GameChallengeService.java
  src/main/java/com/sorisonsoon/gameriddle/domain/repository/GameRiddleRepositoryImpl.java
  src/main/java/com/sorisonsoon/record/domain/entity/Record.java
Labels: ✨ Feature

#33 #11 game logic
  .gitignore
  build.gradle
  requirements.txt
  src/main/java/com/sorisonsoon/common/config/WebConfig.java
  src/main/java/com/sorisonsoon/common/exception/type/ExceptionCode.java
  src/main/java/com/sorisonsoon/common/utils/sentenceSimilarity/MatrixUtils.java
  src/main/java/com/sorisonsoon/gamevoice/controller/GameVoiceController.java
  src/main/java/com/sorisonsoon/gamevoice/domain/entity/GameVoice.java
  src/main/java/com/sorisonsoon/gamevoice/domain/repository/GameVoiceRepository.java
  src/main/java/com/sorisonsoon/gamevoice/domain/repository/GameVoiceRepositoryCustom.java
  src/main/java/com/sorisonsoon/gamevoice/domain/repository/GameVoiceRepositoryImpl.java
  src/main/java/com/sorisonsoon/gamevoice/dto/response/GameVoiceQuestionResponse.java
  src/main/java/com/sorisonsoon/gamevoice/service/GameVoiceService.java
  src/main/java/com/sorisonsoon/record/controller/RecordController.java
  src/main/java/com/sorisonsoon/record/domain/entity/Record.java
  src/main/java/com/sorisonsoon/record/domain/repository/RecordRepository.java
  src/main/java/com/sorisonsoon/record/domain/repository/RecordRepositoryCustom.java
  src/main/java/com/sorisonsoon/record/domain/repository/RecordRepositoryImpl.java
  src/main/java/com/sorisonsoon/record/dto/request/RecordGameVoiceRequest.java
  src/main/java/com/sorisonsoon/record/dto/response/RecordGameVoiceResponse.java
  src/main/java/com/sorisonsoon/record/dto/response/RecordGameVoiceResponseList.java
  src/main/java/com/sorisonsoon/userinfo/domain/entity/UserInfo.java
Labels: ⚙️Setting, ✨ Feature

#40 #39 친구 조회 기능 구현
  src/main/java/com/sorisonsoon/common/exception/type/ExceptionCode.java
  src/main/java/com/sorisonsoon/friend/controller/FriendController.java
  src/main/java/com/sorisonsoon/friend/domain/entity/Friend.java
  src/main/java/com/sorisonsoon/friend/domain/repository/FriendRepository.java
  src/main/java/com/sorisonsoon/friend/domain/repository/FriendRepositoryCustom.java
  src/main/java/com/sorisonsoon/friend/domain/repository/FriendRepositoryImpl.java
  src/main/java/com/sorisonsoon/friend/domain/type/ApplyType.java
  src/main/java/com/sorisonsoon/friend/dto/response/FriendApplyResponse.java
  src/main/java/com/sorisonsoon/friend/dto/response/FriendResponse.java
  src/main/java/com/sorisonsoon/friend/service/FriendService.java
Labels: ✨ Feature

#43 #41 친구 추가 기능
  src/main/java/com/sorisonsoon/friend/controller/FriendController.java
  src/main/java/com/sorisonsoon/friend/domain/entity/Friend.java
  src/main/java/com/sorisonsoon/friend/domain/repository/FriendRepository.java
  src/main/java/com/sorisonsoon/friend/service/FriendService.java
Labels: ✨ Feature

#44 #42 친구 삭제 기능 구현
  config/DDL.sql
  src/main/java/com/sorisonsoon/common/exception/type/ExceptionCode.java
  src/main/java/com/sorisonsoon/friend/controller/FriendController.java
  src/main/java/com/sorisonsoon/friend/domain/entity/Friend.java
  src/main/java/com/sorisonsoon/friend/domain/repository/FriendRepository.java
  src/main/java/com/sorisonsoon/friend/domain/type/FriendStatus.java
  src/main/java/com/sorisonsoon/friend/service/FriendService.java
Labels: ✨ Feature

#49 #48 도소탐 랭킹 및 플레이 기록 저장
  build.gradle
  src/main/java/com/sorisonsoon/common/exception/type/ExceptionCode.java
  src/main/java/com/sorisonsoon/common/utils/sentenceSimilarity/MatrixUtils.java
  src/main/java/com/sorisonsoon/gameChallenge/controller/GameChallengeController.java
  src/main/java/com/sorisonsoon/gameChallenge/domain/entity/GameChallengeSchedule.java
  src/main/java/com/sorisonsoon/gameChallenge/domain/repository/GameChallengeRepositoryCustom.java
  src/main/java/com/sorisonsoon/gameChallenge/domain/repository/GameChallengeRepositoryImpl.java
  src/main/java/com/sorisonsoon/gameChallenge/service/GameChallengeService.java
  src/main/java/com/sorisonsoon/gamevoice/service/GameVoiceService.java
  src/main/java/com/sorisonsoon/ranking/domain/entity/Ranking.java
  src/main/java/com/sorisonsoon/ranking/service/RankingService.java
  src/main/java/com/sorisonsoon/record/domain/entity/Record.java
  src/main/java/com/sorisonsoon/record/domain/repository/RecordRepository.java
Labels: ✨ Feature

#51 #50 맞수수 랭킹 및 플레이 기록 저장
  src/main/java/com/sorisonsoon/gameriddle/controller/GameRiddleController.java
  src/main/java/com/sorisonsoon/gameriddle/dto/request/GameFinishRequest.java
  src/main/java/com/sorisonsoon/gameriddle/service/GameRiddleService.java
  src/main/java/com/sorisonsoon/record/domain/entity/RecordRiddle.java
  src/main/java/com/sorisonsoon/record/domain/repository/RecordRiddleRepository.java
Labels: ✨ Feature

#55 #52 추천 친구 알고리즘 구현
  src/main/java/com/sorisonsoon/friend/controller/FriendController.java
  src/main/java/com/sorisonsoon/friend/domain/repository/FriendRepositoryCustom.java
  src/main/java/com/sorisonsoon/friend/domain/repository/FriendRepositoryImpl.java
  src/main/java/com/sorisonsoon/friend/dto/response/RecommendFriendResponse.java
  src/main/java/com/sorisonsoon/friend/service/FriendService.java
  src/main/java/com/sorisonsoon/gameChallenge/service/GameChallengeService.java
  src/main/java/com/sorisonsoon/interest/domain/entity/Interest.java
Labels: ✨ Feature

#58 #3 로그인 관련 기능
  build.gradle
  src/main/java/com/sorisonsoon/attachedfile/domain/entity/AttachedFile.java
  src/main/java/com/sorisonsoon/comment/domain/entity/Comment.java
  src/main/java/com/sorisonsoon/common/config/BeanConfig.java
  src/main/java/com/sorisonsoon/common/config/QueryDslConfig.java
  src/main/java/com/sorisonsoon/common/config/SecurityConfig.java
  src/main/java/com/sorisonsoon/common/config/SwaggerConfig.java
  src/main/java/com/sorisonsoon/common/controller/SettingTestController.java
  src/main/java/com/sorisonsoon/common/email/controller/EmailController.java
  src/main/java/com/sorisonsoon/common/email/service/EmailService.java
  src/main/java/com/sorisonsoon/common/email/util/EmailValidator.java
  src/main/java/com/sorisonsoon/common/exception/type/ExceptionCode.java
  src/main/java/com/sorisonsoon/common/security/dto/LoginDto.java
  src/main/java/com/sorisonsoon/common/security/dto/TokenDto.java
  src/main/java/com/sorisonsoon/common/security/filter/CustomAuthenticationFilter.java
  src/main/java/com/sorisonsoon/common/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/sorisonsoon/common/security/hadler/JwtAccessDeniedHandler.java
  src/main/java/com/sorisonsoon/common/security/hadler/JwtAuthenticationEntryPoint.java
  src/main/java/com/sorisonsoon/common/security/hadler/LoginFailureHandler.java
  src/main/java/com/sorisonsoon/common/security/hadler/LoginSuccessHandler.java
  src/main/java/com/sorisonsoon/common/security/util/TokenUtils.java
  src/main/java/com/sorisonsoon/community/domain/entity/Community.java
  src/main/java/com/sorisonsoon/friend/domain/entity/Friend.java
  src/main/java/com/sorisonsoon/gameChallenge/domain/entity/GameChallenge.java
  src/main/java/com/sorisonsoon/gameriddle/domain/entity/GameRiddle.java
  src/main/java/com/sorisonsoon/gamevoice/controller/GameVoiceController.java
  src/main/java/com/sorisonsoon/gamevoice/domain/entity/GameVoice.java
  src/main/java/com/sorisonsoon/gamewhisper/domain/entity/GameWhisper.java
  src/main/java/com/sorisonsoon/guestbook/domain/entity/Guestbook.java
  src/main/java/com/sorisonsoon/notice/domain/entity/Notice.java
  src/main/java/com/sorisonsoon/ranking/domain/entity/Ranking.java
  src/main/java/com/sorisonsoon/record/domain/entity/Record.java
  src/main/java/com/sorisonsoon/report/domain/entity/Report.java
  src/main/java/com/sorisonsoon/signsearch/domain/entity/SignSearch.java
  src/main/java/com/sorisonsoon/user/controller/AuthController.java
  src/main/java/com/sorisonsoon/user/controller/UserController.java
  src/main/java/com/sorisonsoon/user/domain/entity/User.java
  src/main/java/com/sorisonsoon/user/domain/repository/UserRepository.java
  src/main/java/com/sorisonsoon/user/domain/type/CustomUser.java
  src/main/java/com/sorisonsoon/user/dto/request/ResetPasswordRequest.java
  src/main/java/com/sorisonsoon/user/dto/request/UserRequest.java
  src/main/java/com/sorisonsoon/user/dto/response/UserResponse.java
  src/main/java/com/sorisonsoon/user/service/AuthService.java
  src/main/java/com/sorisonsoon/user/service/UserService.java
Labels: ⚙️Setting, ✨ Feature

#31 도소탐 ai모델 활용해서 기능 구현 추가 #31
  src/main/java/com/sorisonsoon/gameChallenge/controller/GameChallengeController.java
  src/main/java/com/sorisonsoon/gameChallenge/service/GameChallengeService.java
Labels: ⚙️Setting, ✨ Feature

#61 #61 맞수수 가이드 이미지 오류 해결 및 모델 평가 방법 변경 및 도소탐 제출 기능 수정
  hand_back.py
  src/main/java/com/sorisonsoon/gameChallenge/controller/GameChallengeController.java
  src/main/java/com/sorisonsoon/gameChallenge/domain/repository/GameChallengeRepositoryCustom.java
  src/main/java/com/sorisonsoon/gameChallenge/domain/repository/GameChallengeRepositoryImpl.java
  src/main/java/com/sorisonsoon/gameChallenge/service/GameChallengeService.java
  src/main/java/com/sorisonsoon/gameriddle/controller/GameRiddleController.java
  src/main/java/com/sorisonsoon/gameriddle/domain/repository/GameRiddleRepository.java
  src/main/java/com/sorisonsoon/gameriddle/domain/repository/GameRiddleRepositoryCustom.java
  src/main/java/com/sorisonsoon/gameriddle/domain/repository/GameRiddleRepositoryImpl.java
  src/main/java/com/sorisonsoon/gameriddle/service/GameRiddleService.java
  src/main/java/com/sorisonsoon/record/domain/repository/RecordRepositoryCustom.java
  src/main/java/com/sorisonsoon/record/domain/repository/RecordRepositoryImpl.java
Labels: 🐞Bug, 🔧Refactor

#65 #11 수정된 너목보 게임 로직
  requirements.txt
  src/main/java/com/sorisonsoon/common/config/SecurityConfig.java
  src/main/java/com/sorisonsoon/common/exception/type/ExceptionCode.java
  src/main/java/com/sorisonsoon/gamevoice/controller/GameVoiceController.java
  src/main/java/com/sorisonsoon/gamevoice/domain/entity/GameVoice.java
  src/main/java/com/sorisonsoon/gamevoice/domain/repository/GameVoiceRepositoryCustom.java
  src/main/java/com/sorisonsoon/gamevoice/domain/repository/GameVoiceRepositoryImpl.java
  src/main/java/com/sorisonsoon/gamevoice/dto/response/GameVoiceQuestionResponse.java
  src/main/java/com/sorisonsoon/gamevoice/service/GameVoiceService.java
  src/main/java/com/sorisonsoon/record/domain/repository/RecordRepository.java
  src/main/java/com/sorisonsoon/record/domain/repository/RecordRepositoryImpl.java
  src/main/java/com/sorisonsoon/record/dto/request/RecordGameVoiceRequest.java
Labels: ✨ Feature, 🔧Refactor

#67 #66 huggingface에 모델 올린 후 사용 + CORS 미들웨어 추가
  __pycache__/hand_back.cpython-39.pyc
  hand_back.py
Labels: ⚙️Setting, 🔧Refactor

#64 #59 BE 자동 배포 설정
  .github/workflows/deploy.yml
  .github/workflows/gradle.yml
  dockerfile
  requirements.txt
  src/main/resources/application.yml
Labels: ⚙️Setting

#70 feat: S3Bucket-connect
  build.gradle
  requirements.txt
  simText.py
  src/main/java/com/sorisonsoon/common/config/S3Config.java
  src/main/java/com/sorisonsoon/friend/controller/FriendController.java
  src/main/java/com/sorisonsoon/friend/service/FriendService.java
  src/main/java/com/sorisonsoon/gameChallenge/controller/GameChallengeController.java
  src/main/java/com/sorisonsoon/gameriddle/controller/GameRiddleController.java
  src/main/java/com/sorisonsoon/guestbook/controller/GuestbookController.java
  src/main/java/com/sorisonsoon/guestbook/domain/entity/Guestbook.java
  src/main/java/com/sorisonsoon/guestbook/domain/repository/GuestbookRepository.java
  src/main/java/com/sorisonsoon/guestbook/dto/GuestBookFormDto.java
  src/main/java/com/sorisonsoon/guestbook/service/GuestbookService.java
  src/main/java/com/sorisonsoon/interest/controller/InterestController.java
  src/main/java/com/sorisonsoon/interest/domain/entity/Interest.java
  src/main/java/com/sorisonsoon/interest/domain/repository/InterestRepository.java
  src/main/java/com/sorisonsoon/interest/dto/InterestFormDto.java
  src/main/java/com/sorisonsoon/interest/service/ImageUrlRequest.java
  src/main/java/com/sorisonsoon/interest/service/InterestService.java
  src/main/java/com/sorisonsoon/interest/service/WordCloudService.java
  src/main/java/com/sorisonsoon/user/controller/UserController.java
  src/main/java/com/sorisonsoon/user/domain/entity/FileStorageProperties.java
  src/main/java/com/sorisonsoon/user/domain/entity/User.java
  src/main/java/com/sorisonsoon/user/dto/UserFormDto.java
  src/main/java/com/sorisonsoon/user/dto/response/NickNameUserInfo.java
  src/main/java/com/sorisonsoon/user/service/FileStorageService.java
  src/main/java/com/sorisonsoon/user/service/MailService.java
  src/main/java/com/sorisonsoon/user/service/Response.java
  src/main/java/com/sorisonsoon/user/service/S3Service.java
  src/main/java/com/sorisonsoon/user/service/UserMailResponse.java
  src/main/java/com/sorisonsoon/user/service/UserService.java
Labels: ✨ Feature

#72 #71 통합 작업 및 기능 추가
  .gitignore
  src/main/java/com/sorisonsoon/common/config/SecurityConfig.java
  src/main/java/com/sorisonsoon/common/email/service/EmailService.java
  src/main/java/com/sorisonsoon/gameriddle/controller/GameRiddleController.java
  src/main/java/com/sorisonsoon/membership/controller/MembershipController.java
  src/main/java/com/sorisonsoon/membership/domain/entity/Membership.java
  src/main/java/com/sorisonsoon/membership/domain/repository/MembershipRepository.java
  src/main/java/com/sorisonsoon/membership/service/MembershipService.java
  src/main/java/com/sorisonsoon/payment/controller/PaymentController.java
  src/main/java/com/sorisonsoon/payment/domain/entity/Payment.java
  src/main/java/com/sorisonsoon/payment/domain/repository/PaymentRepository.java
  src/main/java/com/sorisonsoon/payment/dto/MembershipDTO.java
  src/main/java/com/sorisonsoon/payment/dto/PaymentDTO.java
  src/main/java/com/sorisonsoon/payment/gateway/ExamplePaymentGatewayClient.java
  src/main/java/com/sorisonsoon/payment/service/PaymentService.java
  src/main/java/com/sorisonsoon/ranking/controller/RankingController.java
  src/main/java/com/sorisonsoon/ranking/domain/entity/Ranking.java
  src/main/java/com/sorisonsoon/ranking/domain/repository/RankingRepository.java
  src/main/java/com/sorisonsoon/ranking/domain/repository/RankingRepositoryCustom.java
  src/main/java/com/sorisonsoon/ranking/domain/repository/RankingRepositoryImpl.java
  src/main/java/com/sorisonsoon/ranking/dto/RankingDTO.java
  src/main/java/com/sorisonsoon/ranking/dto/response/RankResponse.java
  src/main/java/com/sorisonsoon/ranking/service/RankingService.java
Labels: ✨ Feature, 🔧Refactor

#74 #73 너목보 버그 수정
  src/main/java/com/sorisonsoon/gamevoice/domain/repository/GameVoiceRepositoryImpl.java
Labels: 🐞Bug
